name: BE CI
on:
  push:
    branches: [feature/ci-cd]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Move into backend directory
        working-directory: ./apps/backend
        run: |
          echo "Now in backend directory"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_KEY }}

      - name: Build docker image
        working-directory: ./apps/backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-app:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-app:latest
